export enum ModalActionType {
  SIGN_IN_TO_JOIN = 'SIGN_IN_TO_JOIN',
  SIGN_IN = 'SIGN_IN',
  JOIN = 'JOIN',
  CANT_JOIN = 'CANT_JOIN',
  RESIGN = 'RESIGN',
  THANKS_FOR_PAYING = 'THANKS_FOR_PAYING',
  PAY = 'PAY',
  OWNER_CANT_DO_THIS = 'OWNER_CANT_DO_THIS',
  CREATE_EVENT = 'CREATE_EVENT'
}
