image: domnyk/chrome-ng-cli:6.2.3

stages:
  - build
  - test
  - release

Build app:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn run build

Test:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn run test:ci

Release:
  stage: release
  script:
    - yarn -v
  when: manual

