image: domnyk/chrome-ng-cli:6.2.3

stages:
  - build
  - test
  - release

Build app:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn run build

Test:
  stage: test
  before_script:
    # Install Chrome to use headless browser. In futere, I need to make own image with headless Chrome
    - yarn install
  script:
    - yarn run test
#
# Release:
#   stage: release
#   before_script:
#     - apk --update add ruby ruby-dev
#     - gem install --no-document json
#     - gem install --no-document dpl
#   script:
#     - dpl --provider=heroku --app=$HEROKU_PROJECT_NAME --api-key=$HEROKU_API_KEY
#   only:
#     - master
#   when: manual

