language: node_js
node_js:
  - "10.11.0"

cache: yarn

stages:
  - "Build"
  - "Test"
  - name: "Release"
  - if: branch = master


jobs:
  include:
    - stage: "Build"
      before_install:
        - yarn global add @angular/cli
      script: yarn run build
    - stage: "Test"
      script: yarn run test:ci
    - stage: "Release"
      script: skip
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: vinci-11235813






