language: node_js
node_js:
  - "10.11.0"

stages:
  - "Build"
  - "Test"
  - name: "Release"
  - if: branch = master


jobs:
  include:
    - stage: "Build"
      before_install:
        - yarn global add @angular/cli
      script: yarn run build




